CPFA-1 Create react infrastructure
bejalane/codeway-poetry-fe pull request #1
Opened 2022-01-11 14:53 UTC by KenAdams777

1) set up redux and file structure
2) set up routing

2022-01-11 16:08 UTC, MuscularSloth approved these changes
Залил себе, проинсталил, запустил. Все работает.
По структуре вроде тоже все нормально.

2022-01-11 16:10 UTC, bejalane requested changes
Great job, please see some comments.

2022-01-11 16:10 UTC, bejalane commented on public/index.html
> -    <link rel="manifest" href="%PUBLIC_URL%/manifest.json" />
Why do we need to remove this? and also manifest file? We don't need it too much but anyway better to keep it also with manifest.json file

2022-01-12 09:09 UTC, KenAdams777 commented on public/index.html
> -    <link rel="manifest" href="%PUBLIC_URL%/manifest.json" />
Do you mean restore only 'manifest' or icons too?

2022-01-12 09:23 UTC, KenAdams777 commented on src/App.js
> +				<h1>WELCOME TO THE CODEWAY POETRY APP</h1>
Done.

2022-01-12 09:23 UTC, KenAdams777 commented on src/App.scss
> +h1 {
Done.

2022-01-12 09:23 UTC, KenAdams777 commented on src/components/AnnounceAuthor/AnnounceAuthor.js
> +import './style__AnnounceAuthor.scss';
Done.

2022-01-12 09:56 UTC, bejalane commented on public/index.html
> -    <link rel="manifest" href="%PUBLIC_URL%/manifest.json" />
Up to you, this is not so necessary. You can remove it all or to restore it.

2022-01-12 09:56 UTC, bejalane approved these changes
Great job!

2022-01-12 09:59 UTC, merged