CPA-21 Get and Render Poems List
bejalane/codeway-poetry-fe pull request #12
Opened 2022-01-22 00:37 UTC by RudeAnna

Here I "got" poems list and rendered poems on Home page.
Poem Creation Date and Excerpt are moved to tickets #62 and #64.

2022-01-22 04:45 UTC, KenAdams777 requested changes
You have done a great job here! Like the way you organize your code.
Leave some comments and suggestions, hope it will be useful.

2022-01-22 04:45 UTC, KenAdams777 commented on src/components/Poem/Poem.js
> +import viewsIcon from "../../img/views-icon.svg";
All these icons should be png format, no need to use svg here.

2022-01-22 04:45 UTC, KenAdams777 commented on src/redux/rootReducer.js
>  import loginReducer from "./login/loginReducer";
@RudeMax  why is it just 'loginReducer', maybe it's better to call it 'authReducer' since there is not only login logic but registration as well.

2022-01-22 04:45 UTC, KenAdams777 commented on src/redux/poems/poemsAsyncActions.js
> +		return axios(requestOptions)
Not sure but I think no reason to put a return here. 
@bejalane please correct me if I'm wrong.

2022-01-22 04:45 UTC, KenAdams777 commented on src/components/PoemsList/PoemsList.js
> +				<p className="PoemsList__header__text">Poems</p>
As long as it's title better to wrap it into `<h2>/<h3>...` tags.

2022-01-22 04:45 UTC, KenAdams777 commented on src/components/Poem/Poem.js
> +					{poem.author.fullname}
Here should be the optional chaining operator as well, I think.

2022-01-22 04:45 UTC, KenAdams777 commented on src/components/Poem/Poem.js
> +					{poem.tags.map((tag) => {
Better to add condition here if there are any tags at all.

2022-01-22 04:45 UTC, KenAdams777 commented on src/components/Poem/Poem.js
> +							<div key={Math.random()} className="Poem__tag-container">
In my humble opinion using` uuid v4()` is a better approach than `Math.random()`.

2022-01-22 06:23 UTC, KenAdams777 requested changes
One more as I think a good idea to be implemented.

2022-01-22 06:23 UTC, KenAdams777 commented on src/components/PoemsList/PoemsList.js
> +					poemsList.map((poem) => {
Before rendering all poems, here is a good practice to add the `conditional operator "?"` to have an option conditionally display `loadingSpiner` if it takes a while to get a response from the server, or to display an `errorMessage` if the server returned an error.

2022-01-22 08:56 UTC, MuscularSloth reviewed
Great job! Take a look at the comment section please =)

2022-01-22 08:56 UTC, MuscularSloth commented on src/components/Poem/Poem.js
> +import viewsIcon from "../../img/views-icon.svg";
I think SVG is better, at least we can control their color by CSS. For example for hover or active states

2022-01-22 08:56 UTC, MuscularSloth commented on src/components/PoemsList/PoemsList.js
> +					poemsList.map((poem) => {
You already have  `isFetching` in reducer, so you can just check it. 

```
const isPoemsFetching = useSelector((state) => state?.poems?.isFetching);
...
...
{isPoemsFetching ? 
  <Loader... >
  : 
  poemsList ? poemsList.map((poem) => {<Poem key={poem.id} poem={poem} />}) : 'Poems not found'
}
```

2022-01-22 08:56 UTC, MuscularSloth commented on src/redux/poems/poemsReducer.js
> +				error: action.payload,
I think we need `...state,` here

2022-01-22 08:56 UTC, MuscularSloth commented on src/redux/rootReducer.js
> +  modals: modalsReducer,
Check formatting =)

2022-01-22 08:56 UTC, MuscularSloth commented on src/scss/commonVariables.scss
> +@mixin poemTag {
Now is OK, but there will be conflicts after merging `CPA-61 Common Variables Fix` #11 , to solve them in future part with mixin needs to move in `commonMixins.scss` that will appear after merging. And check files when you need to `@import` it.

2022-01-22 09:33 UTC, KenAdams777 requested changes

2022-01-22 09:33 UTC, KenAdams777 commented on src/components/PoemsList/PoemsList.js
> +					poemsList.map((poem) => {
> You already have `isFetching` in reducer, so you can just check it.
> 
> ```
> const isPoemsFetching = useSelector((state) => state?.poems?.isFetching);
> ...
> ...
> {isPoemsFetching ? 
>   <Loader... >
>   : 
>   poemsList ? poemsList.map((poem) => {<Poem key={poem.id} poem={poem} />}) : 'Poems not found'
> }
> ```

Exactly, that's my point. But also better to add jsx for an error case.

2022-01-22 14:09 UTC, RudeAnna commented on src/components/Poem/Poem.js
> +					{poem.author.fullname}
@KenAdams777 you mean poem?.fullname, poem?.author, poem?.tags etc?

2022-01-22 14:10 UTC, RudeAnna commented on src/components/Poem/Poem.js
> +							<div key={Math.random()} className="Poem__tag-container">
oh, yes, it was a temporary solution, I'll change that. Thanks

2022-01-22 14:12 UTC, RudeAnna commented on src/components/PoemsList/PoemsList.js
> +				<p className="PoemsList__header__text">Poems</p>
ok, that's a good point for better readability @KenAdams777

2022-01-22 14:15 UTC, RudeAnna commented on src/components/PoemsList/PoemsList.js
> +					poemsList.map((poem) => {
Thanks for the suggestion, it's brilliant I think. I'll implement this into the component. Anyway I'll need to make a <Loader /> component for my next ticket

2022-01-22 14:17 UTC, RudeAnna commented on src/redux/poems/poemsReducer.js
> +				error: action.payload,
oh, thanks, it definitely should be there

2022-01-22 14:19 UTC, RudeAnna commented on src/redux/rootReducer.js
> +  modals: modalsReducer,
There was a conflict so it formated this way after resolving...))) Will change it back to normal

2022-01-22 14:22 UTC, RudeAnna commented on src/scss/commonVariables.scss
> +@mixin poemTag {
I see , but it's a @RudeMax 's code. There was a conflict. 
I think when commonMixins.scss are created all mentions of mixins have to be checked

2022-01-22 14:33 UTC, RudeAnna commented on src/components/PoemsList/PoemsList.js
> +					poemsList.map((poem) => {
Thanks for the suggestion, it's brilliant I think. I'll implement this into the component. Anyway I'll need to make a Loader component for my next ticket

2022-01-22 23:24 UTC, RudeMax commented on src/components/Poem/Poem.js
> +							<div key={Math.random()} className="Poem__tag-container">
Yep, uuid is already preinstalled if I am not mistaken

2022-01-23 12:13 UTC, KenAdams777 approved these changes
You've done a great job!
Seems to me all is good!

2022-01-23 23:10 UTC, MuscularSloth approved these changes
Great job!

2022-01-24 00:52 UTC, RudeMax approved these changes

2022-01-24 04:13 UTC, KenAdams777 commented on src/redux/poems/poemsActions.js
> +	GET_POEMS_SUCCESS,
> Not sure if we have any convention for types, I have made like FETCH_BLA_BLA whereas Anna has GET_BLA_BLA is it important? @bejalane

@RudeMax  Good question. I think it's better to call types the same as it calls at the postman: `GET, POST, PULL...`, so then it will be the same for all of us.

2022-01-24 08:40 UTC, bejalane commented on src/redux/poems/poemsAsyncActions.js
> +		return axios(requestOptions)
not reason. we will move it to the separate function, but after this task, we will do it as a separate ticket

2022-01-24 08:46 UTC, bejalane commented on src/redux/poems/poemsActions.js
> +	GET_POEMS_SUCCESS,
You can call it whatever you want, but if you get smth it is logical to write GET_... , if you update smth it is better to write UPDATE_...  and not patch or post, actions are for us, for human beings, so we just need to give readable names. 
But if it is async action the suffix should be the same, and let's close it like here: 
FAILURE
SUCCESS
REQUEST

2022-01-24 08:52 UTC, bejalane requested changes
Great job, plz check a couple of comments.

2022-01-24 08:52 UTC, bejalane commented on src/components/Loader/Loader.js
> +        <Box sx={{ display: 'flex' }}>
Why are we using BOX? I thought we discussed not to use MUI layouts, only modals and some complicated things, no?

2022-01-24 08:52 UTC, bejalane commented on src/components/PoemsList/PoemsList.js
> +	const poemsList = useSelector((state) => state?.poems?.poemsList?.items);
no need to use optional chaining for redux state.

2022-01-24 08:52 UTC, bejalane commented on src/pages/HomePage/HomePage.js
> +	});
use here empty array as a second param.

2022-01-24 08:52 UTC, bejalane commented on src/redux/poems/poemsAsyncActions.js
> +		const requestOptions = {
Please create a separate ticket to make unified API request function

2022-01-24 09:08 UTC, bejalane commented
@RudeAnna  also your branch has conflicts. For `package-lock.json` you can just copy it from `main` branch and replace your local file as is and commit it, this way you will unload changes from this file. Next meeting i'll tell you all how to deal with this files, cz they can have conflicts very often

2022-01-24 12:33 UTC, RudeAnna commented on src/components/Loader/Loader.js
> +        <Box sx={{ display: 'flex' }}>
I thought a Circular Loader is the component that would be more convenient to use  from mui that to write it yourself...

2022-01-25 14:17 UTC, KenAdams777 requested changes
Good job!
Please take a look at two minor comments I've left.

2022-01-25 14:17 UTC, KenAdams777 commented on src/components/Menu/Menu.scss
>  		background: $colorMenuBackground;
According to the convention should be a Kebab-case here.

2022-01-25 14:17 UTC, KenAdams777 commented on src/components/PoemsList/PoemsList.js
> +	const poemsList = useSelector((state) => state.poems.poemsList?.items);
Missed one more question here.

2022-01-25 14:20 UTC, RudeAnna commented on src/components/PoemsList/PoemsList.js
> +	const poemsList = useSelector((state) => state.poems.poemsList?.items);
Where?

2022-01-25 14:21 UTC, RudeAnna commented on src/components/Menu/Menu.scss
>  		background: $colorMenuBackground;
When I pulled main brunch there was $boxShadow in CommonVariables. That's not my task to change the names of scss variables to kebab-case

2022-01-25 14:32 UTC, KenAdams777 commented on src/components/PoemsList/PoemsList.js
> +	const poemsList = useSelector((state) => state.poems.poemsList?.items);
> Where?

`state.poems.poemsList?.items` or it should be here?

2022-01-25 14:36 UTC, KenAdams777 commented on src/components/Menu/Menu.scss
>  		background: $colorMenuBackground;
> When I pulled main brunch there was $boxShadow in CommonVariables. That's not my task to change the names of scss variables to kebab-case

It's strange coz seems like it's been a few days since @MuscularSloth  merged those changes to the main branch and all variables named via Kebab-case.

2022-01-25 15:43 UTC, RudeAnna commented on src/components/Menu/Menu.scss
>  		background: $colorMenuBackground;
Also it's even not in the component I've been assigned to. I had to change to the available variable in ComVars as it has been throving an error

2022-01-25 16:45 UTC, KenAdams777 approved these changes

2022-01-25 17:15 UTC, bejalane approved these changes

2022-01-25 17:24 UTC, merged