CPA-17 AUTH Login
bejalane/codeway-poetry-fe pull request #13
Opened 2022-01-24 00:58 UTC by RudeMax

I have added a login modal. Rename reducer will be separate ticket. On SUBMIT LOGIN only logs in user, further actions will be added on more clearance.

2022-01-24 05:43 UTC, KenAdams777 requested changes
Great job!
I've left some thoughts and suggestions in the comments, hope at least some of them will be useful.

2022-01-24 05:43 UTC, KenAdams777 commented on src/components/Modals/Login/Login.js
> +		dispatch(fetchLogin(email, password));
1. Here before dispatching the action it would be good to add a condition to check if any field is empty and show a warning in such a case.
2. Also here is the place to clean inputs, coz if you open the login modal again then fields will be filled with previous info.
3. The `fetchLogin` name doesn't actually mutch to the logic of action, you don't fetch the data from the server you're actually trying to send it there.

2022-01-24 05:43 UTC, KenAdams777 commented on src/components/Modals/Login/Login.js
> +						<a href="/forgot-password">Forgot password?</a>
As I remember 'forgot password' is gonna have a separate route, so it would be good to use `<Link to=" ">` here.

2022-01-24 05:43 UTC, KenAdams777 commented on src/components/Modals/Registration/Registration.js
>  import { fetchRegistration } from "../../../redux/login/loginActions";
Same point as about `fetchLogin` name of action.

2022-01-24 05:43 UTC, KenAdams777 commented on src/components/Modals/Login/Login.scss
> +	background: $colorWhite;
The name of the variable should be according to a convention.

2022-01-24 05:43 UTC, KenAdams777 commented on src/components/Modals/Login/Login.scss
> +	box-shadow: $boxShadow;
SAB

2022-01-24 05:43 UTC, KenAdams777 commented on src/components/Modals/Login/Login.scss
> +			color: $colorInactiveText;
SAB

2022-01-24 05:43 UTC, KenAdams777 commented on src/components/Modals/Login/Login.scss
> +			background: $colorWhite;
SAB

2022-01-24 05:43 UTC, KenAdams777 commented on src/components/Modals/Login/Login.scss
> +				color: $colorAlertError;
SAB

2022-01-24 05:43 UTC, KenAdams777 commented on src/components/Modals/Login/Login.scss
> +			color: $colorLinkText;
SAB

2022-01-24 05:43 UTC, KenAdams777 commented on src/components/Modals/Login/Login.scss
> +				color: $colorLinkText;
SAB

2022-01-24 05:43 UTC, KenAdams777 commented on src/components/Modals/Login/Login.scss
> +				background-color: $colorWhite;
SAB

2022-01-24 05:43 UTC, KenAdams777 commented on src/components/Modals/Registration/Registration.scss
> +				background-color: $colorWhite;
SAB

2022-01-24 05:43 UTC, KenAdams777 commented on src/redux/login/loginActions.js
>  	FETCH_REGISTRATION_FAILURE,
1. The name of the file doesn't provide actual information, here is not only login action also registration as well. It should be an `auth` folder with `authActions.js`, I think.
2. Also the issue with the `FETCH_` name I mentioned above.

2022-01-24 09:00 UTC, bejalane commented on src/components/Modals/Login/Login.js
> +						<a href="/forgot-password">Forgot password?</a>
yes, it should be router link, or it will cause app refresh

2022-01-24 11:11 UTC, MuscularSloth reviewed
Great job! =)
Please read suggestion below.

2022-01-24 11:11 UTC, MuscularSloth commented on src/redux/login/loginActions.js
> +		dispatch({ type: FETCH_LOGIN_SUCCESS, payload: response.data });
Suggestion: 
As variant you can use action creators for this.  

> Action creators have two primary purposes:
> 
> They prepare and format the contents of action objects
> They encapsulate any additional work needed whenever we create those actions

For example you can collect all the actions in separate file and export them:

```
export function successUserLogin(data) {
    return{
        type: FETCH_LOGIN_SUCCESS,
        payload: data
    }
}

```

and then import it when you need

`dispatch(successUserLogin(response.data));`

This is standard pattern, you can read about it here:
https://redux.js.org/tutorials/fundamentals/part-7-standard-patterns#action-creators

2022-01-24 14:06 UTC, RudeMax commented on src/components/Modals/Login/Login.js
> +		dispatch(fetchLogin(email, password));
Great points: 
1. My submit button is not active if any fields are empty + there is a warning under each field in this case.
2. How could I forgot about clearing the fields... Than you, will fix it asap.
3. Emmm kinda makes sense. But we still get a user object in return. Let me consult the boss.

2022-01-25 01:35 UTC, RudeAnna commented on src/redux/login/loginActions.js
> +		dispatch({ type: FETCH_LOGIN_SUCCESS, payload: response.data });
I always use action creators even though Max's way looks like less syntax, creators are more readable

2022-01-25 01:38 UTC, RudeAnna reviewed
Overall looks great! After implementing other's suggestions it must do

2022-01-26 00:54 UTC, RudeMax commented on src/components/Modals/Login/Login.js
> +		dispatch(fetchLogin(email, password));
the fields are auto cleaned due to it being a MUI component. I have checked.

2022-01-26 02:04 UTC, RudeMax commented on src/redux/login/loginActions.js
> +		dispatch({ type: FETCH_LOGIN_SUCCESS, payload: response.data });
Makes sense, I just don't understand if there is a point for a separate file here, when we only have two actions. Anyway will get familiar to this and change in future. Let me talk to @bejalane

2022-01-26 04:31 UTC, KenAdams777 approved these changes

2022-01-26 12:11 UTC, MuscularSloth approved these changes
Gogogo

2022-01-26 13:17 UTC, bejalane approved these changes

2022-01-26 13:47 UTC, merged