CPFA-32 COMMON: Navigation bar
bejalane/codeway-poetry-fe pull request #2
Opened 2022-01-12 16:54 UTC by KenAdams777

2022-01-12 19:42 UTC, bejalane requested changes
Great job 👍 
take a look to some comments please

2022-01-12 19:42 UTC, bejalane commented on src/components/Authors/Authors.js
> +import React from 'react';
Why should you do Authors? you need make only Nav bar. This is the task for someone else. 
Next time if you want to prepare dummy component just put there title only and that's it. You can leave it as it is, no worries.

2022-01-12 19:42 UTC, bejalane commented on src/components/Menu/Menu.scss
> +	box-shadow: 0px 4px 5px rgba(0, 0, 0, 0.14), 0px 1px 10px rgba(0, 0, 0, 0.12),
let's create file something like "common-variables.scss" where styles like box-shadow will be a mixin / variable. After in all the places where you want to use it you need to import this file and use mixin / variable only, not to duplicate styles.

2022-01-12 19:42 UTC, bejalane commented on src/components/Menu/Menu.scss
> +	z-index: 666;
it should't be high number, this is bad practice. It should be the minimal number which solves you z-index problem

2022-01-12 19:42 UTC, bejalane commented on src/components/Menu/Menu.scss
> +	border-radius: 4px;
this is better to move to common variables as well

2022-01-12 19:42 UTC, bejalane commented on src/components/NavigationBar/NavigationBar.js
> +	const [burberMenuToggle, setBurberMenuToggle] = useState('close');
typo in "**burber**MenuToggle" -> burger

2022-01-12 19:42 UTC, bejalane commented on src/components/NavigationBar/NavigationBar.js
> +	const [burberMenuToggle, setBurberMenuToggle] = useState('close');
if you are using strings you should make a constant like
```
const menuStates = {
  CLOSE: 'close',
  OPEN: 'open'
}
```
and use it after like: 
menuStates.CLOSE instead of raw string 'close'. 

But this is not a case at all to use it, it is better to use boolean value and rename state like: 
`const [isMenuOpen, setIsMenuOpen] = useState(false);`

2022-01-12 19:42 UTC, bejalane commented on src/components/NavigationBar/NavigationBar.js
> +			<div className="navBar__container">
class name in BEM for react components is better to start from the same component name despite BEM convention.

component name is `NavigationBar` so the classname should be `NavigationBar__container` 
the same for all other classes in all the components, will not repeat this comment.

2022-01-12 19:42 UTC, bejalane commented on src/components/NavigationBar/NavigationBar.js
> +							setBurberMenuToggle(
Change here to boolean according to the previous comment

2022-01-12 19:42 UTC, bejalane commented on src/components/NavigationBar/NavigationBar.js
> +						<span className={burberMenuToggle}></span>
You can take it to the separate component and send with props isMenuOpen state, and there make the logic.

2022-01-12 19:42 UTC, bejalane commented on src/components/NavigationBar/NavigationBar.js
> +			{burberMenuToggle === 'open' && <Menu />}
same here, it will be` {burberMenuToggle && <Menu />}`

2022-01-12 19:42 UTC, bejalane commented on src/components/NavigationBar/NavigationBar.scss
> +.navBar {
According to the previous comment here should be the name of the component.

2022-01-12 19:42 UTC, bejalane commented on src/components/NavigationBar/NavigationBar.scss
> +		.open:nth-child(1) {
This is also should be taken to the separate component with triple span tag from above

2022-01-12 20:03 UTC, MuscularSloth requested changes

2022-01-12 20:03 UTC, MuscularSloth commented on src/App.scss
> +
This can be useful

```
a:not([class]),
a:not([class]):active,
a:not([class]):visited,
a:not([class]):hover{
    color: inherit;
}

a{
    text-decoration: none;
}

button,
input[type="button"],
input[type="reset"],
input[type="submit"]{
    -webkit-appearance: none;
}
```

2022-01-12 20:05 UTC, bejalane commented on src/components/Authors/Authors.js
> +							src="./img/author-img.jpg"
this is really not important here since the image will come from api, so we can left it as it is right now

2022-01-12 20:06 UTC, bejalane commented on src/components/NavigationBar/NavigationBar.js
> +								src="./img/current-user-img.jpg"
SAB

2022-01-12 20:08 UTC, bejalane commented on src/components/NavigationBar/NavigationBar.js
> +							src="./img/logo-poetry.svg"
Good point, with SVG we can do after the separate component to export all SVGs, and from there we can import what we need by name. But for now it is better to import as Kostya commented.

2022-01-12 20:08 UTC, bejalane commented on src/components/Menu/Menu.scss
> +
all colors also should be in common-variables.scss file

2022-01-12 20:09 UTC, bejalane commented on src/App.scss
> +
this is smth for general styles, no?

2022-01-12 20:13 UTC, MuscularSloth commented on src/components/Authors/Authors.js
> +							src="./img/author-img.jpg"
I understand, but this is too hard to test now because we get empty images which break the whole layout. Maybe we should use some mock data for testing?

2022-01-12 20:28 UTC, MuscularSloth commented on src/App.scss
> +
> this is smth for general styles, no?

Yes. It will help a lot in future.

2022-01-12 21:47 UTC, MuscularSloth reviewed
Just another comment =)

2022-01-12 21:47 UTC, MuscularSloth commented on src/components/NavigationBar/NavigationBar.scss
> +		flex-wrap: wrap;
Why do we need this? 

`flex-wrap: wrap;`

I think it's a redundant rule

2022-01-13 09:08 UTC, KenAdams777 commented on src/components/Authors/Authors.js
> +import React from 'react';
There is item '2) Authors' in the current task' card. Misunderstood and thought that I need to do this component either.

2022-01-13 09:29 UTC, KenAdams777 commented on src/components/Menu/Menu.scss
> +	box-shadow: 0px 4px 5px rgba(0, 0, 0, 0.14), 0px 1px 10px rgba(0, 0, 0, 0.12),
Done.

2022-01-13 09:32 UTC, KenAdams777 commented on src/components/Menu/Menu.scss
> +	border-radius: 4px;
Done.

2022-01-13 09:38 UTC, KenAdams777 commented on src/components/NavigationBar/NavigationBar.js
> +			<div className="navBar__container">
Done.

2022-01-13 09:40 UTC, KenAdams777 commented on src/components/NavigationBar/NavigationBar.scss
> +.navBar {
Done.

2022-01-13 10:05 UTC, KenAdams777 commented on src/components/Authors/Authors.js
> +							src="./img/author-img.jpg"
MuscularSloth, thx for the suggestion, it helped to fix the defect.
Actually, I've added those images temporarily in order to style the component layout, and in the future, we will just need to add the map method.

2022-01-13 10:25 UTC, KenAdams777 commented on src/components/Menu/Menu.scss
> +	z-index: 666;
> it should't be high number, this is bad practice. It should be the minimal number which solves you z-index problem

actually, in this case, z-index doesn't resolve the problem at all, the 'menu' component's still displayed behind the 'authors' component but should be in front, and I don't know how to fix this. Does anyone have a solution?

2022-01-13 10:26 UTC, KenAdams777 commented on src/components/Authors/Authors.js
> +import React from 'react';
> Why should you do Authors? you need make only Nav bar. This is the task for someone else :) Next time if you want to prepare dummy component just put there title only and that's it. For now you can leave it as it is, no worries.

There is item '2) Authors' in the current task' card. Misunderstood and thought that I need to do this component either.

2022-01-13 10:28 UTC, KenAdams777 commented on src/components/NavigationBar/NavigationBar.js
> +								src="./img/current-user-img.jpg"
Done.

2022-01-13 10:28 UTC, KenAdams777 commented on src/components/NavigationBar/NavigationBar.js
> +								src="./img/icon_notif.png"
Done.

2022-01-13 10:41 UTC, KenAdams777 commented on src/components/NavigationBar/NavigationBar.js
> +							src="./img/logo-poetry.svg"
> SVG we can insert like ReactComponent
> 
> `import {ReactComponent as LogoPoetry} from './img/logo-poetry.svg'`
> 
> And then
> 
> ```
> <Link to="/" className="navBar__logo-link">
>     <LogoPoetry />
> </Link>
> ```

Did so, but it's not displayed at all now.

2022-01-13 11:04 UTC, KenAdams777 commented on src/components/NavigationBar/NavigationBar.js
> +							src="./img/logo-poetry.svg"
> SVG we can insert like ReactComponent
> 
> `import {ReactComponent as LogoPoetry} from './img/logo-poetry.svg'`
> 
> And then
> 
> ```
> <Link to="/" className="navBar__logo-link">
>     <LogoPoetry />
> </Link>
> ```

Done.

2022-01-13 11:09 UTC, KenAdams777 commented on src/components/Menu/Menu.scss
> +	z-index: 666;
> > it should't be high number, this is bad practice. It should be the minimal number which solves you z-index problem
> 
> actually, in this case, z-index doesn't resolve the problem at all, the 'menu' component's still displayed behind the 'authors' component but should be in front, and I don't know how to fix this. Does anyone have a solution?

Resolved.
No need to use z-index just needed to add background.

2022-01-13 11:11 UTC, KenAdams777 commented on src/components/Menu/Menu.scss
> +
> I think you should add
> 
> `background-color: #FFFFFF;`

Thx for the hint, it helped.

2022-01-13 11:13 UTC, KenAdams777 commented on src/App.scss
> +	width: 100%;
Done.

2022-01-13 11:16 UTC, KenAdams777 commented on src/App.scss
> +
Done.

2022-01-13 11:17 UTC, KenAdams777 commented on src/components/NavigationBar/NavigationBar.scss
> +		flex-wrap: wrap;
> Why do we need this?
> 
> `flex-wrap: wrap;`
> 
> I think it's a redundant rule

You are right. Already deleted.

2022-01-13 13:31 UTC, KenAdams777 commented on src/components/NavigationBar/NavigationBar.js
> +	const [burberMenuToggle, setBurberMenuToggle] = useState('close');
Done.

2022-01-13 14:47 UTC, KenAdams777 commented on src/components/NavigationBar/NavigationBar.js
> +	const [burberMenuToggle, setBurberMenuToggle] = useState('close');
> if you are using strings you should make a constant like
> 
> ```
> const menuStates = {
>   CLOSE: 'close',
>   OPEN: 'open'
> }
> ```
> 
> and use it after like: menuStates.CLOSE instead of raw string 'close'.
> 
> But this is not a case at all to use it, it is better to use boolean value and rename state like: `const [isMenuOpen, setIsMenuOpen] = useState(false);`

Done.

2022-01-13 14:48 UTC, KenAdams777 commented on src/components/NavigationBar/NavigationBar.js
> +							setBurberMenuToggle(
> Change here to boolean according to the previous comment

Done.

2022-01-13 14:48 UTC, KenAdams777 commented on src/components/NavigationBar/NavigationBar.js
> +						<span className={burberMenuToggle}></span>
> You can take it to the separate component and send with props isMenuOpen state, and there make the logic with classes.

Done.

2022-01-13 14:50 UTC, KenAdams777 commented on src/components/NavigationBar/NavigationBar.js
> +			{burberMenuToggle === 'open' && <Menu />}
> same here, it will be` {burberMenuToggle && <Menu />}`

Here is a problem. React sends the warning:
Warning: Received `true` for a non-boolean attribute `div`.

2022-01-13 14:51 UTC, KenAdams777 commented on src/components/NavigationBar/NavigationBar.scss
> +		.open:nth-child(1) {
> This is also should be taken to the separate component with triple span tag from above

Done.

2022-01-13 15:25 UTC, MuscularSloth reviewed
Good job! 

What do you think about my comment below?

2022-01-13 15:25 UTC, MuscularSloth commented on src/scss/commonVariables.scss
> +
Little suggestion:
Maybe we should somehow concretize variables names? For example what should we do if we have another border-radius in another element that have different value? I think would be better if we have names like

`$borderRadius4px: 4px;`
`$borderRadius50pct: 50%;`

For colors it can be like

`$colorBtnGreen: rgb(112, 141, 230);`
`$colorBtnGreenHover: rgb(70, 81, 21);`

`$colorWhite: #ffffff;`

Than when other person who didn't know about those variables will start type "$color"  IDE will show all the available colors of project automatically.

Same thing about shadows and other future variables

2022-01-13 16:04 UTC, alexiStructShare requested changes
Now it looks much better and clearer! 
Take a look at some minor comments and I think this is the last iteration! You did great! Just a lot of of comments for code and files organization fell on you :) But you nailed it!  🥇

2022-01-13 16:04 UTC, alexiStructShare commented on src/components/Authors/Authors.scss
> +.authors {
Sorry but if we are already here, please let's make it similar to all the cases. it should be Authors with capital letter.

2022-01-13 16:04 UTC, alexiStructShare commented on src/components/NavigationBar/NavigationBar.js
> +					{logoContainer()}
Don't need to refactor, but it can be a component in separate file.

2022-01-13 16:04 UTC, alexiStructShare commented on src/components/NavigationBar/NavigationBar.js
> +					style={{ justifyContent: 'space-around' }}
Let's make all styles inside scss files and not inline

2022-01-13 16:04 UTC, alexiStructShare commented on src/components/NavigationBar/NavigationBar.js
> +		setIsMenuOpen(!isMenuOpen);
GREAT!

2022-01-14 12:35 UTC, bejalane approved these changes
🥇 Amazing job Andrew!!!! You can squash and merge!

2022-01-14 12:35 UTC, alexiStructShare approved these changes

2022-01-14 12:36 UTC, merged