CPA-75 Endpoints constructor
bejalane/codeway-poetry-fe pull request #21
Opened 2022-02-05 13:37 UTC by MuscularSloth

-Add Endpoints constructor
-Add new logic to Recover Password page as example
-Implement suggestions from last PR
-Fix some issues

2022-02-05 20:23 UTC, bejalane requested changes
Good job, please fix some things

2022-02-05 20:23 UTC, bejalane commented on src/services/utils/endpointsConstuctor.js
> +const getTokenFromLocalStorage = (fieldName) => {
1) Why this function is named like that if the logic is general? 
2) Do we really need it separate? 
3) I don't know what do you save in LS but I think it is user object, and if so - it has to be JSON.parse to get an object and get from this object the token

2022-02-05 20:23 UTC, bejalane commented on src/services/utils/endpointsConstuctor.js
> +		return {
remove return, it can be returned without, since there is no logic above return. Same for the next function

2022-02-05 20:23 UTC, bejalane commented on src/services/utils/endpointsConstuctor.js
> +			headers: createHeader(header.type, header.hasToken),
this is per endpoint, you don't need to pass here any logic, just do  control it straight in params. like:
`createHeader(false, false),`

2022-02-05 20:23 UTC, bejalane commented on src/services/utils/endpointsConstuctor.js
> +			data: {
no need to pass and map data here, this function is just for url construction, method and headers. 
Data construction should be inside component.

2022-02-05 20:23 UTC, bejalane commented on src/services/utils/endpointsConstuctor.js
> + *	header:
according to what i wrote before please remove it

2022-02-05 20:23 UTC, bejalane commented on src/services/utils/endpointsConstuctor.js
> + *	data: {} // can be empty
data should be attached inside thunk function, no reason to pass data to this function

2022-02-07 08:16 UTC, KenAdams777 requested changes

2022-02-07 12:50 UTC, alexiStructShare commented on src/services/utils/endpointsConstuctor.js
> +		headers: createHeader(params.header),
params.header is not right here

2022-02-07 12:50 UTC, alexiStructShare commented on src/pages/RecoverPasswordPage/RecoverPasswordPage.js
> +		dispatch(getRecoverPassword(getEnpointConfig(endpointParams), data));
please use getEndpointConfig inside a thunk function

2022-02-07 12:56 UTC, bejalane approved these changes

2022-02-07 12:57 UTC, merged