CPA-64 POEMS excerpt
bejalane/codeway-poetry-fe pull request #22
Opened 2022-02-07 17:22 UTC by RudeAnna

2022-02-07 19:58 UTC, KenAdams777 approved these changes

2022-02-08 01:40 UTC, RudeMax approved these changes

2022-02-08 08:07 UTC, bejalane requested changes

2022-02-08 08:07 UTC, bejalane commented on src/components/PoemsList/PoemsList.js
> +						return <Poem key={uuidv4()} poem={poem} />;
this is not right, it will cause re-rendering of whole poems' list

2022-02-08 14:15 UTC, RudeAnna commented on src/components/PoemsList/PoemsList.js
> +						return <Poem key={uuidv4()} poem={poem} />;
got it, will change back

2022-02-08 14:30 UTC, MuscularSloth approved these changes

2022-02-08 15:09 UTC, bejalane approved these changes

2022-02-08 15:10 UTC, merged