CPA-79 Duplicate poems rendering
bejalane/codeway-poetry-fe pull request #24
Opened 2022-02-08 17:01 UTC by KenAdams777

Here I've fixed the bugs, seems to me it works. Still have a minor issue with redundant requests, I'm gonna work on it later on.

2022-02-08 17:04 UTC, MuscularSloth approved these changes
looks good

2022-02-08 17:24 UTC, alexiStructShare requested changes

2022-02-08 17:24 UTC, alexiStructShare commented on src/components/PoemsList/PoemsList.js
> +			dispatch(clearPoemsList());
why do you need to create clear function and dispatch it before call if you can create another action to get poems? 
Theoretically in this case you can have accidental error from BE, and you will end up without poems at all

2022-02-08 17:25 UTC, yuriy1901 approved these changes

2022-02-08 17:50 UTC, RudeAnna commented on src/redux/poems/poemsReducer.js
> +			};
I also think that clearing the list of poems in a separate action might be harmful. I see the problem in this line in
GET_POEMS_SUCCESS case:
poemsList: [...state.poemsList, ...action.payload.items],

shouldn't we just have 
poemsList: action.payload.items,

2022-02-08 17:50 UTC, RudeAnna commented on src/redux/poems/poemsReducer.js
> +			};
I also think that clearing the list of poems in a separate action might be harmful. I see the problem in this line in
GET_POEMS_SUCCESS case:
poemsList: [...state.poemsList, ...action.payload.items],

shouldn't we just have 
poemsList: action.payload.items,

2022-02-08 17:50 UTC, RudeAnna commented on src/redux/poems/poemsReducer.js
> +			};
I also think that clearing the list of poems in a separate action might be harmful. I see the problem in this line in
GET_POEMS_SUCCESS case:
poemsList: [...state.poemsList, ...action.payload.items],

shouldn't we just have 
poemsList: action.payload.items,

2022-02-08 20:36 UTC, KenAdams777 commented on src/redux/poems/poemsReducer.js
> +			};
> I also think that clearing the list of poems in a separate action might be harmful. I see the problem in this line in GET_POEMS_SUCCESS case: poemsList: [...state.poemsList, ...action.payload.items],
> 
> shouldn't we just have poemsList: action.payload.items,

In order to keep scrolling, it's needed to combine the previous state and payload otherwise we just replace the state with a new batch of data.

2022-02-08 20:48 UTC, KenAdams777 commented on src/redux/poems/poemsReducer.js
> +	poemsListInfiniteScroll: [],
This is redundant, remove it.

2022-02-08 20:48 UTC, KenAdams777 commented on src/redux/poems/poemsReducer.js
> +	poemsListInfiniteScroll: [],
> This is redundant, remove it.

I know. Just forgot to remove it.

2022-02-08 22:25 UTC, bejalane approved these changes
I am approving in advance with comments

2022-02-08 22:25 UTC, bejalane commented on src/components/PoemsList/PoemsList.js
> +			dispatch(getPoemsListInfiniteScroll(requestOptions));
from where you get request options? 
we need to use new general function to create request options. But anyway, in order to merge PR ASAP please create a separate ticket to fix it after.

2022-02-08 22:25 UTC, bejalane commented on src/redux/poems/poemsAsyncActions.js
> +// export const getPoemsListInfiniteScroll = (reguestOptions) =>
do you need all these comments?

2022-02-08 22:25 UTC, bejalane commented on src/redux/poems/poemsAsyncActions.js
> +export const getPoemsListInfiniteScroll = (requestOptions) =>
i think this is a duplication of code, you can add parameter here 
`getPoems = (requestOptions, isInfiniteScroll) => ...` 
where infinite scroll is boolean, and then you have logic smth like that: 
`const onSuccessFn = isInfiniteScroll ? getPoemsListSuccessInfiniteScroll : getPoemsListSuccess;`

2022-02-08 22:29 UTC, RudeAnna approved these changes

2022-02-09 05:52 UTC, KenAdams777 commented on src/redux/poems/poemsAsyncActions.js
> +export const getPoemsListInfiniteScroll = (requestOptions) =>
> i think this is a duplication of code, you can add parameter here `getPoems = (requestOptions, isInfiniteScroll) => ...` where isInfiniteScroll is boolean, and then you have logic smth like that: `const onSuccessFn = isInfiniteScroll ? getPoemsListSuccessInfiniteScroll : getPoemsListSuccess;`

Agree, good idea.

2022-02-09 07:12 UTC, merged