CPA-62 Date rendering
bejalane/codeway-poetry-fe pull request #31
Opened 2022-02-11 12:47 UTC by yuriy1901

2022-02-11 14:15 UTC, MuscularSloth approved these changes

2022-02-11 14:15 UTC, bejalane requested changes

2022-02-11 14:15 UTC, bejalane commented on src/components/Poem/Poem.js
> +			<Moment format="MMMM Do YYYY">
Please move format to constants

2022-02-11 14:18 UTC, bejalane commented on src/components/Poem/Poem.js
> +			<Moment format="MMMM Do YYYY">
According to design there are couple of options to display

2022-02-16 04:17 UTC, KenAdams777 approved these changes

2022-02-16 04:17 UTC, KenAdams777 commented on src/services/utils/renderDataFormat.js
> +}
Nothing wrong, just the ternary operator would be more concise.

2022-02-16 12:21 UTC, bejalane commented on src/services/utils/renderDataFormat.js
> +}
1) you can do it just like that: 
`return (currentTimeInMs - poemCreatedInMs > 6.048e+8)`

2) what is the purpose of this function?

2022-02-16 12:27 UTC, yuriy1901 commented on src/services/utils/renderDataFormat.js
> +}
this function checks if more than a week has passed since the publication. And in the component, depending on this, a different date format is displayed

2022-02-16 12:38 UTC, bejalane commented on src/services/utils/renderDataFormat.js
> +}
So since it returns only Boolean it doesn't change anything. Please give this function the proper name

2022-02-16 13:23 UTC, bejalane approved these changes

2022-02-16 13:25 UTC, merged