CPA-31 Display Author Page
bejalane/codeway-poetry-fe pull request #35
Opened 2022-02-15 20:08 UTC by MuscularSloth

-Add Author Page component
-Add Author Page Poems List component (cause we have diff template for this)
-Add Author Follow component
-Add Author Follows Modal component
-Add formatData in utils (temporary until cpa-62)
-Fix bug in poems reducer

2022-02-15 23:06 UTC, RudeMax approved these changes
Wow, seems like a lot of work! Great job. Looking forward to QA it

2022-02-16 05:56 UTC, KenAdams777 requested changes
Great job here!
Left some minor comments and suggestions.

2022-02-16 05:56 UTC, KenAdams777 commented on src/pages/AuthorPage/AuthorPage.js
> +	let { authorName } = useParams();
why it is `let`? Are you gonna rewrite the `value`? )

2022-02-16 05:56 UTC, KenAdams777 commented on src/pages/AuthorPage/AuthorPage.scss
> +	}
Isn't the avatar should be round?

2022-02-16 05:56 UTC, KenAdams777 commented on src/pages/AuthorPage/AuthorPagePoemsList/AuthorPagePoemsList.js
> +	}, [authorSlug]);
We are duplicating logic here. Wouldn't it be better to reuse the `AuthorPage` logic created by @yuriy1901 (code is identic) and just render different `jsx` as a `{children}` props?

2022-02-16 05:56 UTC, KenAdams777 commented on src/redux/authorInfo/authorInfoActions.js
> +};
I guess the name of types should also tell what are you doing with `AUTHOR_INFO` are you trying to get or post it. In this particular case it's obvious but still )

2022-02-16 05:56 UTC, KenAdams777 commented on src/redux/authorInfo/authorInfoReducer.js
> +		case AUTHOR_INFO_REQUEST:
Because here its becoming not that obvious )

2022-02-16 05:56 UTC, KenAdams777 commented on src/redux/authorInfo/authorInfoReducer.js
> +				authorData: { ...action.payload },
I've been asking Max the same question, just wanted to know what is the reason to use the spread operator here?

2022-02-16 05:56 UTC, KenAdams777 commented on src/services/utils/formatDateTime.js
> +//TODO: TEMPORARY SOLUTION UNTIL CPA-62 WILL BE IMPLEMENTED
I guess you can already use logic by @yuriy1901 here.

2022-02-16 12:35 UTC, bejalane requested changes

2022-02-16 12:35 UTC, bejalane commented on src/pages/AuthorPage/AuthorFollows/followsPlaceholders.js
> +export const followsPlaceholder = [
followMock is better naming for such things and better to create separate folder with mocks if needed

2022-02-16 12:35 UTC, bejalane commented on src/pages/AuthorPage/AuthorFollowsModal/AuthorFollowsModal.js
> +						X
I think it is better use CSS or some icon

2022-02-16 12:35 UTC, bejalane commented on src/pages/AuthorPage/AuthorFollowsModal/AuthorFollowsModal.js
> +							{usersList.length > 0 &&
`usersList.length > 0` can be just `usersList.length`

2022-02-16 12:35 UTC, bejalane commented on src/pages/AuthorPage/AuthorFollowsModal/AuthorFollowsModal.js
> +									<li key={idx} className="AuthorFollowsModal__item">
key here is loop index?

2022-02-16 12:35 UTC, bejalane commented on src/pages/AuthorPage/AuthorPage.js
> +		const endPointUserParams = {
i'm still confused why do you build it inside component and not inside thunk function? it is not related to the component

2022-02-16 12:35 UTC, bejalane commented on src/pages/AuthorPage/AuthorPage.js
> +			loginInfo?.isAuthenticated &&
why do you need isAuthenticated ? 
I think this is enough to check if there is currentUser

2022-02-16 12:35 UTC, bejalane commented on src/pages/AuthorPage/AuthorPage.js
> +	const loginInfo = useSelector((state) => state.login);
why do you need to bring whole object?

2022-02-16 12:35 UTC, bejalane commented on src/pages/AuthorPage/AuthorPage.js
> +			setIsThisOwnProfile(true);
it can be written like that 
```
const isOwnProfile = currentUser && currentUser?.id === authorInfo?.authorData?.id;
setIsThisOwnProfile(isOwnProfile)
```

2022-02-16 12:35 UTC, bejalane commented on src/pages/AuthorPage/AuthorPage.js
> +		checkIfThisOwnProfile(loginInfo, authorInfo);
why do you need to pass the args if you take it from selectors?

2022-02-16 12:35 UTC, bejalane commented on src/pages/AuthorPage/AuthorPagePoemsList/AuthorPagePoemsList.js
> +	const endPointPoemsParams = {
SAB

2022-02-16 12:35 UTC, bejalane commented on src/redux/authorInfo/authorInfoReducer.js
> +		case AUTHOR_INFO_REQUEST:
GET_AUTHOR_DATA_... is better i think

2022-02-16 12:35 UTC, bejalane commented
Good job, Kostya! But please take care of comments

2022-02-16 13:07 UTC, MuscularSloth commented on src/pages/AuthorPage/AuthorFollowsModal/AuthorFollowsModal.js
> +									<li key={idx} className="AuthorFollowsModal__item">
> key here is loop index?

Yes for now. I left the comment above 
`// TODO: change idx to user?.id when will be actual data`

2022-02-16 13:26 UTC, MuscularSloth commented on src/pages/AuthorPage/AuthorPage.js
> +		const endPointUserParams = {
> i'm still confused why do you build it inside component and not inside thunk function? it is not related to the component

Config builds inside thunk. Here I just pass params.

2022-02-16 20:13 UTC, bejalane requested changes

2022-02-16 20:13 UTC, bejalane commented on src/pages/AuthorPage/AuthorPagePoemsList/AuthorPagePoemsList.js
> +							<Link to={`/poem/${poem?.slug}`}>
shouldn't it be a const?

2022-02-16 20:13 UTC, bejalane commented on src/pages/AuthorPage/AuthorPagePoemsList/AuthorPagePoemsList.js
> +								<Link to={`/poem/${poem?.slug}`}>{poem?.title}</Link>
SAB const?

2022-02-16 20:13 UTC, bejalane commented on src/redux/poems/poemsAsyncActions.js
>  		endpointName: "getPoemsListByAuthorEndpoint",
same here, move this logic to thunk func

2022-02-16 21:00 UTC, MuscularSloth commented on src/redux/poems/poemsAsyncActions.js
>  		endpointName: "getPoemsListByAuthorEndpoint",
But it is already here =)

2022-02-17 09:29 UTC, bejalane commented on src/redux/poems/poemsAsyncActions.js
>  		endpointName: "getPoemsListByAuthorEndpoint",
So what? You can't touch this code?))

2022-02-17 09:29 UTC, bejalane approved these changes

2022-02-17 10:00 UTC, KenAdams777 approved these changes

2022-02-17 10:01 UTC, merged