Yura/pc 44 author follow user
bejalane/codeway-poetry-fe pull request #76
Opened 2022-06-14 07:18 UTC by yuriy1901

2022-06-14 08:03 UTC, bejalane commented on src/pages/AuthorPage/AuthorPage.js
> +			if (authorFollowersId?.includes(currentUser.id)) {
you can make it in 1 line instead of whole if/else
`setIsFollowAuthor(authorFollowersId?.includes(currentUser.id)); `

2022-06-14 08:05 UTC, bejalane commented on src/services/utils/endpointsConstuctor.js
> +	getFollowUserEndpoint: ({ urlArgs }) => ({
you can make one endpoint, since it is only true/false changes in the end. And just pass true or false (as a string) as a urlParam

2022-06-14 08:06 UTC, bejalane commented on src/redux/authorInfo/authorInfoReducer.js
> +				console.log(action.payload);
remove

2022-06-14 08:06 UTC, bejalane commented on src/redux/authorInfo/authorInfoAsyncActions.js
> +export const getAuthorFollowAsync = (authorName) => {
you can left only 1 thunk and just pass here true or false as a param

2022-06-16 11:40 UTC, yuriy1901 commented on src/pages/AuthorPage/AuthorPage.js
> +			checkIfUserFollow();
> checkIfCurrentUserIsFollower

yes, it has more logic)

2022-06-16 11:53 UTC, yuriy1901 commented on src/pages/AuthorPage/AuthorFollows/AuthorFollows.js
> +						<p className="AuthorFollows__usertype">
> I think this code is not reachable after return

you are right, fixed

2022-06-16 12:11 UTC, yuriy1901 commented on src/pages/AuthorPage/AuthorPage.js
> +			if (authorFollowersId?.includes(currentUser.id)) {
> you can make it in 1 line instead of whole if/else `setIsFollowAuthor(authorFollowersId?.includes(currentUser.id)); `

yep, it will be cleaner

2022-06-16 14:38 UTC, yuriy1901 commented on src/services/utils/endpointsConstuctor.js
> +	getFollowUserEndpoint: ({ urlArgs }) => ({
> you can make one endpoint, since it is only true/false changes in the end. And just pass true or false (as a string) as a urlParam

done

2022-06-16 20:25 UTC, bejalane requested changes

2022-06-16 20:25 UTC, bejalane commented on src/pages/AuthorPage/AuthorPage.js
> +				setModalUsers(modalUsers);
what is the difference between these 3 (39-41) rows and rows 33-35?

2022-06-16 20:25 UTC, bejalane commented on src/pages/AuthorPage/AuthorPage.js
> +			const authorFollowersId = authorFollowers?.map((el) => el.id);
authorFollowersId -> authorFollowersId**s**

2022-06-16 20:25 UTC, bejalane commented on src/pages/AuthorPage/AuthorPage.js
> +					<div className="AuthorPage__follow-button-wrapper">
you have duplicated block where the only change is button text. So please change conditionally only button text

2022-06-16 20:25 UTC, bejalane commented on src/redux/authorInfo/authorInfoReducer.js
> +	GET_AUTHOR_FOLLOW_REQUEST,
I don't see the usage in reducer

2022-06-16 20:25 UTC, bejalane commented on src/redux/authorInfo/authorInfoReducer.js
> +			return {
you can make only one action for Follow/Unfollow just passing to reducer isFollow variable and according to its value you can  modify the followers (remove author or add).

2022-06-17 11:27 UTC, yuriy1901 commented on src/pages/AuthorPage/AuthorPage.js
> +			const authorFollowersId = authorFollowers?.map((el) => el.id);
> authorFollowersId -> authorFollowersId**s**

done

2022-06-18 13:20 UTC, yuriy1901 commented on src/pages/AuthorPage/AuthorPage.js
> +				setModalUsers(modalUsers);
> what is the difference between these 3 (39-41) rows and rows 33-35?

i have optimized the code

2022-06-18 13:53 UTC, yuriy1901 commented on src/pages/AuthorPage/AuthorPage.js
> +					<div className="AuthorPage__follow-button-wrapper">
> you have duplicated block where the only change is button text. So please change conditionally only button text

done

2022-06-18 14:41 UTC, yuriy1901 commented on src/redux/authorInfo/authorInfoReducer.js
> +			return {
done

2022-06-18 14:41 UTC, yuriy1901 commented on src/redux/authorInfo/authorInfoReducer.js
> +	GET_AUTHOR_FOLLOW_REQUEST,
done

2022-06-19 10:09 UTC, bejalane requested changes
Great job, just take care please of the last small comments and you can merge

2022-06-19 10:09 UTC, bejalane commented on src/redux/authorInfo/authorInfoReducer.js
> +			if (action.payload.responseOptions.is_follow === true) {
Here you can return state once. 
You need here only one thing - to mutate the followers. So conditionally mutate the followers first and after return the state (since it is similar both times)

2022-06-19 10:09 UTC, bejalane commented on src/redux/authorInfo/authorInfoReducer.js
> +			console.log(action.payload);
remove

2022-06-20 19:31 UTC, merged