CPFA-53 Added Error boundary
bejalane/codeway-poetry-fe pull request #8
Opened 2022-01-20 07:07 UTC by KenAdams777

Added Error boundary. And also a little change of NavBar styling into user isn't logged in case.

2022-01-20 09:23 UTC, MuscularSloth approved these changes
As for me all is well. Great job!

2022-01-20 11:44 UTC, alexiStructShare requested changes

2022-01-20 11:44 UTC, alexiStructShare commented on src/components/ErrorBoundary/ErrorBoundary.js
> +		console.log(error);
why do we need console.log here?

2022-01-20 11:44 UTC, alexiStructShare commented on src/components/Menu/Menu.js
> +	const handleLogout = () => {};
this is just a preparation for logout?

2022-01-20 11:44 UTC, alexiStructShare commented on src/components/NavigationBar/NavigationBar.js
>  					<button className="NavigationBar__signIn-btn">Sign In</button>
Instead of only styling the button I think it is better to use separate component for the button

2022-01-20 11:44 UTC, alexiStructShare commented on src/scss/commonVariables.scss
> +$colorMenuBackground: #ffffff;
with such specification of the name there is no point in common variables. 
I think color palette should have just colors:
```
$color-white
$color-blue-main
$color-blue-secondary
```

etc

2022-01-20 12:42 UTC, KenAdams777 commented on src/components/NavigationBar/NavigationBar.js
>  					<button className="NavigationBar__signIn-btn">Sign In</button>
> Instead of only styling the button I think it is better to use separate component for the button

Do you mean to create a separate "Button" component in order to reuse one in other components, or just to create a separate 'SingInButton' component?
Also all the styles for the button in 'commonVariables ' scss file as a mixin.

2022-01-20 12:42 UTC, KenAdams777 commented on src/scss/commonVariables.scss
> +$colorMenuBackground: #ffffff;
> with such specification of the name there is no point in common variables. I think color palette should have just colors:
> 
> ```
> $color-white
> $color-blue-main
> $color-blue-secondary
> ```
> 
> etc

We were discussing that topic at the last meeting and made a conclusion that is the better way to name colors by their components. So it is easier to change the value of color it needed. Maybe Yurii could explain better the idea.

2022-01-20 12:42 UTC, KenAdams777 commented on src/components/ErrorBoundary/ErrorBoundary.js
> +		console.log(error);
> why do we need console logs here?

In case a user is curious enough, he/she can open a console to check what exactly went wrong.
Should I remove it?

2022-01-20 23:02 UTC, RudeAnna commented on src/scss/commonVariables.scss
>  @mixin button {
I'd create two mixins for buttons:
1. one for large button, for "Add Poem", "Login" and "Create author announce"
2. another for the rest small buttons, as "Edit", "Follow", "Sign In" and so on
They have different sizes, so padding, height and border radius are different
For small button 
padding: 10px 20px;
height: 30px;
border-radiuis: 15px;
For large button:
padding-top: 20px;
padding-bottom: 20px;
height: 64px;
border-radius: 32px;

It could be great to discuss common variables again during the next meeting, as it is a hot topic that gives a lot of commotion

2022-01-20 23:03 UTC, RudeAnna commented on src/scss/commonVariables.scss
>  @mixin button {
I'd create two mixins for buttons:

one for large button, for "Add Poem", "Login" and "Create author announce"
another for the rest small buttons, as "Edit", "Follow", "Sign In" and so on
They have different sizes, so padding, height and border radius are different
For small button
padding: 10px 20px;
height: 30px;
border-radiuis: 15px;
For large button:
padding-top: 20px;
padding-bottom: 20px;
height: 64px;
border-radius: 32px;
It could be great to discuss common variables again during the next meeting, as it is a hot topic that gives a lot of commotion

2022-01-20 23:03 UTC, RudeAnna commented on src/scss/commonVariables.scss
>  @mixin button {
I'd create two mixins for buttons:

one for large button, for "Add Poem", "Login" and "Create author announce"
another for the rest small buttons, as "Edit", "Follow", "Sign In" and so on
They have different sizes, so padding, height and border radius are different
For small button
padding: 10px 20px;
height: 30px;
border-radiuis: 15px;
For large button:
padding-top: 20px;
padding-bottom: 20px;
height: 64px;
border-radius: 32px;
It could be great to discuss common variables again during the next meeting, as it is a hot topic that gives a lot of commotion

2022-01-20 23:06 UTC, RudeAnna commented on src/scss/commonVariables.scss
>  	cursor: pointer;
I'd create two mixins for buttons:

one for large button, for "Add Poem", "Login" and "Create author announce"
another for the rest small buttons, as "Edit", "Follow", "Sign In" and so on
They have different sizes, so padding, height and border radius are different
For small button
padding: 10px 20px;
height: 30px;
border-radiuis: 15px;
For large button:
padding-top: 20px;
padding-bottom: 20px;
height: 64px;
border-radius: 32px;
It could be great to discuss common variables again during the next meeting, as it is a hot topic that gives a lot of commotion

2022-01-21 00:35 UTC, RudeMax approved these changes
Seems like a great job.

2022-01-21 05:23 UTC, KenAdams777 commented on src/scss/commonVariables.scss
>  	cursor: pointer;
Good idea. It should be discussed one more time at the next meeting.

2022-01-21 05:24 UTC, KenAdams777 commented on src/scss/commonVariables.scss
>  	cursor: pointer;
> I'd create two mixins for buttons:
> 
> one for large button, for "Add Poem", "Login" and "Create author announce" another for the rest small buttons, as "Edit", "Follow", "Sign In" and so on They have different sizes, so padding, height and border radius are different For small button padding: 10px 20px; height: 30px; border-radiuis: 15px; For large button: padding-top: 20px; padding-bottom: 20px; height: 64px; border-radius: 32px; It could be great to discuss common variables again during the next meeting, as it is a hot topic that gives a lot of commotion

Good idea. It should be discussed one more time at the next meeting.

2022-01-21 13:12 UTC, alexiStructShare commented on src/components/ErrorBoundary/ErrorBoundary.js
> +		console.log(error);
yes

2022-01-21 13:13 UTC, alexiStructShare commented on src/components/NavigationBar/NavigationBar.js
>  					<button className="NavigationBar__signIn-btn">Sign In</button>
not SignIn button, just Button with options

2022-01-21 13:16 UTC, alexiStructShare commented on src/scss/commonVariables.scss
>  	cursor: pointer;
@RudeAnna @KenAdams777 please organize next meeting

2022-01-21 14:21 UTC, KenAdams777 commented on src/components/NavigationBar/NavigationBar.js
>  					<button className="NavigationBar__signIn-btn">Sign In</button>
> not SignIn button, just Button with options

Maybe it would be better to add a separate ticket with a description, coz honestly I'm not really clear what exactly do you mean and how it should looks like?

2022-01-21 14:50 UTC, merged