#15 registration
bejalane/codeway-poetry-fe pull request #9
Opened 2022-01-20 13:56 UTC by RudeMax

2022-01-20 14:37 UTC, MuscularSloth reviewed
Great Job! Please take a look at the comments below.

2022-01-20 14:37 UTC, MuscularSloth commented on src/components/Modals/Registration/Registration.js
> +  const [emailError, setEmailError] = useState("Email field can't be dirty");
Why dirty? =)

2022-01-20 14:37 UTC, MuscularSloth commented on src/components/Modals/Registration/Registration.js
> +            <TextField
I suggest to divide all those fields with their logic into separate components. If you do so, we'll be able to reuse them on other pages. 
For example I need email input in my tasks and I could use your.

And you need to use password and email fields in your next task

2022-01-20 14:37 UTC, MuscularSloth commented on src/components/Modals/Registration/Registration.js
> +  const [nameDirty, setNameDirty] = useState(false);
For Boolean variables I suggest use names like `isNameDirty` it is more readable

2022-01-20 14:37 UTC, MuscularSloth commented on src/components/Modals/Registration/Registration.js
> +            {nameDirty && nameError && (
I didn't find where this variable sets to false again. Is this message will be show permanently?

2022-01-20 15:14 UTC, MuscularSloth commented on src/components/Modals/Registration/Registration.js
> +            <TextField
Even more. It can be one component with different props. And its behavior can depend on props. What do you think?

2022-01-20 15:30 UTC, KenAdams777 reviewed
You've done a great job!
I leave some comments and questions, please take a look.

2022-01-20 15:30 UTC, KenAdams777 commented on src/redux/login/loginActions.js
> +};
Maybe it is better to create a separate reducer for the open and close action so it can be reusable to any modal.

2022-01-20 15:30 UTC, KenAdams777 commented on src/redux/login/loginActions.js
> +  };
In my humble opinion then. catch. construction is more concise and readable. But it's optional so it's up to you.

2022-01-20 15:30 UTC, KenAdams777 commented on src/redux/login/loginReducer.js
> +  username: "",
Could you please explain where do we use the 'username' field?

2022-01-20 15:30 UTC, RudeMax commented on src/components/Modals/Registration/Registration.js
> +  const [emailError, setEmailError] = useState("Email field can't be dirty");
Will fix to empty

2022-01-20 15:32 UTC, RudeMax commented on src/components/Modals/Registration/Registration.js
> +            <TextField
Not 100% clear on how exactly to divide but we can discuss in detail in pm. But I agree.

2022-01-20 15:35 UTC, RudeMax commented on src/components/Modals/Registration/Registration.js
> +            {nameDirty && nameError && (
You mean the error message? It disappears as soon as the field is valid

2022-01-20 15:41 UTC, RudeMax commented on src/components/Modals/Registration/Registration.js
> +        console.log("empty");
Oh of course no, just forgot to remove

2022-01-20 15:42 UTC, RudeMax commented on src/components/Modals/Registration/Registration.js
> +  const [showPassword, setShowPassword] = useState(false);
Yep

2022-01-20 15:43 UTC, RudeMax commented on src/components/Modals/Registration/Registration.js
> +              onClick={handleSubmit}
Yeah, was thinking about that, will do, but heard from someone that this is not so important, will change anyway

2022-01-20 15:44 UTC, RudeMax commented on src/components/Modals/Registration/Registration.js
> +            <a href="/">Have an account? Log in here...</a>
Why?

2022-01-20 15:44 UTC, RudeMax commented on src/scss/commonVariables.scss
> +$alertErrorColor: #ee2126;
True, thanx

2022-01-20 15:45 UTC, RudeMax commented on src/redux/login/loginActions.js
> +};
Let's discuss it

2022-01-20 15:46 UTC, RudeMax commented on src/redux/login/loginActions.js
> +  };
This is just the way I am used to doing it

2022-01-20 15:47 UTC, RudeMax commented on src/redux/login/loginReducer.js
> +  username: "",
I don't use it yet, it was there already when I pulled the main brunch, just forgot to remove.

2022-01-20 15:47 UTC, KenAdams777 commented on src/components/Modals/Registration/Registration.js
> +
Don't we need any validator to avoid user with name ')))__|\\\\||||@@###' or something similar ). I think it would be good to add validation something like `const usernameValidRegex = /^(?=[a-zA-Z._]{3,12}$)(?!.*[_.]{2})[^_.].*[^_.]$/;` and use if statement to check is name valid or not.

2022-01-20 15:47 UTC, KenAdams777 commented on src/components/Modals/Registration/Registration.js
> +    setPassword(e.target.value);
Same as with name validation.

2022-01-20 15:51 UTC, MuscularSloth commented on src/components/Modals/Registration/Registration.js
> +            {nameDirty && nameError && (
Ok, but it doesn't depend on `nameDirty` only on `nameError `   as I understand this part of code. If I am right, what for `nameDirty` is needed?

2022-01-20 15:53 UTC, KenAdams777 commented on src/components/Modals/Registration/Registration.js
> +            <a href="/">Have an account? Log in here...</a>
> Why?

so we can link it to any page we need with react-router-dom.
Im not insisting, I'm just sharing my thoughts, because I'm just a student dame as you are  ))

2022-01-20 15:54 UTC, RudeMax commented on src/components/Modals/Registration/Registration.js
> +            {nameDirty && nameError && (
Name dirty indicates that the field was in focus already

2022-01-20 15:57 UTC, KenAdams777 commented on public/index.html
> +    />
I'm just curious which way is common: to add it in the app.scss file or its better to do as you have done at index file.

2022-01-20 16:15 UTC, bejalane requested changes
Great job! 👍  left you some comments.

2022-01-20 16:15 UTC, bejalane commented on src/redux/login/loginActions.js
> +// export const fetchLogin = (username, password) => async (dispatch) => {
remove unneeded comments

2022-01-20 16:15 UTC, bejalane commented on src/redux/login/loginActions.js
> +};
yes, agree, it should be some separate reducer for modals.

2022-01-20 16:22 UTC, RudeMax commented on src/components/Modals/Registration/Registration.js
> +    (state) => state?.login?.isRegistrationOpen
Yep initial. Perebdel)

2022-01-20 16:28 UTC, bejalane commented on src/components/Modals/Registration/Registration.js
> +
let's add it as a separate ticket

2022-01-20 17:51 UTC, yuriy1901 approved these changes

2022-01-20 17:51 UTC, yuriy1901 commented on src/components/Modals/Registration/Registration.js
> +            <a href="/">Have an account? Log in here...</a>
> 

I think too "Link" will be right decision

2022-01-20 21:44 UTC, RudeMax commented on public/index.html
> +    />
Yep, I am also curious but it didn't actually want to work without it
@bejalane what do you think?

2022-01-20 22:02 UTC, RudeMax commented on src/components/Modals/Registration/Registration.js
> +            <a href="/">Have an account? Log in here...</a>
I was also not offensive just asking because I am a student as you are))) Thanx

2022-01-20 22:52 UTC, RudeMax commented on src/components/Modals/Registration/Registration.js
> +            <a href="/">Have an account? Log in here...</a>
But I still don't understand why do we need link here, these are just modals and this element will just toggle to Login modal, so when I make a login modal I will probably make it just onClick. What do you think?

2022-01-20 23:49 UTC, RudeMax commented on package.json
> +    "@emotion/styled": "^11.6.0",
It was a part of MUI installation package, I tried npm uninstall but it doesn't want to work without it

2022-01-21 00:06 UTC, RudeMax commented on src/components/Modals/Registration/Registration.js
> +
Good point, I have done it, not sure that perfectly

2022-01-21 11:20 UTC, KenAdams777 requested changes
I've left some comments and suggestions. Hope it will be useful.
I think some of them should be discussed with theBoss ).

2022-01-21 11:20 UTC, KenAdams777 commented on src/redux/modals/madalsReducer.js
> +import { OPEN_REGISTRATION, CLOSE_REGISTRATION } from "./madalsTypes";
Here is a typo in the name of the components: mOdalsTypes, mOdalsReducer.

2022-01-21 11:20 UTC, KenAdams777 commented on src/redux/modals/madalsReducer.js
> +        ...state,
Here is no need to copy state as long as your state has only one field.

2022-01-21 11:20 UTC, KenAdams777 commented on src/redux/modals/madalsReducer.js
> +        ...state,
SAB.

2022-01-21 11:20 UTC, KenAdams777 commented on src/redux/modals/madalsTypes.js
> +export const CLOSE_REGISTRATION = "CLOSE_REGISTRATION";
I think it should be just `OPEN_MODAL` and `CLOSE_MODAL`, so we can reuse this flag to open any modal in the app, not only registration but also Login, etc.

2022-01-21 12:42 UTC, MuscularSloth commented on src/components/Modals/Registration/Registration.js
> +    /(?=^.{6,}$)((?=.*\d)|(?=.*\W+))(?![.\n])(?=.*[A-Z])(?=.*[a-z]).*$/;
Maybe we should extract validation logic in separate function? It will help us to prevent code duplication in other components.

2022-01-21 13:00 UTC, alexiStructShare commented on src/redux/modals/madalsTypes.js
> +export const CLOSE_REGISTRATION = "CLOSE_REGISTRATION";
In this case we need to specify which modal is open, because all modals will be triggered to open or close.

2022-01-21 13:02 UTC, alexiStructShare commented on src/components/Modals/Registration/Registration.js
> +    /(?=^.{6,}$)((?=.*\d)|(?=.*\W+))(?![.\n])(?=.*[A-Z])(?=.*[a-z]).*$/;
Let's make it still in the separate ticket, **please** listen to this point. We can be stuck forever with such things.

2022-01-21 13:06 UTC, alexiStructShare commented on src/components/Modals/Registration/Registration.js
>      } else if (!e.target.value.includes("@")) {
move it to separate ticket!

2022-01-21 13:06 UTC, alexiStructShare commented on src/components/Modals/Registration/Registration.js
> +
move it to separate ticket!

2022-01-21 13:11 UTC, alexiStructShare commented on src/components/Modals/Registration/Registration.js
> +              onClick={handleSubmit}
it is really not so important is this case

2022-01-21 13:12 UTC, alexiStructShare commented on src/components/Modals/Registration/Registration.js
> +            <a href="/">Have an account? Log in here...</a>
we have modals that can appear in every place of over application, they don't need to have route. So no link there

2022-01-21 14:54 UTC, alexiStructShare commented on src/redux/login/loginActions.js
> +  };
again it is payload

2022-01-21 14:54 UTC, alexiStructShare commented on src/components/Modals/Registration/Registration.js
> +            <a href="/">Have an account? Log in here...</a>
did you removed link?

2022-01-21 15:28 UTC, merged